### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by bialystok** [evansm7/umac#5]
I found a System German 5.3 but not Polish.
Is possible making a Polish translation of system 5.3 ?
I can translate communicats, exist Chicago font from 7.5 
(last is https://www.macintoshrepository.org/32816-system-6-0-7-pl_pl-     **6.0.7** )

lets make a Polish version, better than Apple ;)

**Comment by evansm7** [comment]
Thanks for the suggestion but this isn’t directly relevant to this project (and may read onto copyright issues I don’t want to think about); closing as not specific to umac. You might well get interest in this on the 68kmla though, worth a try!
