### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by mix127** [evansm7/umac#6]
Mac can use 256K or more?

include/meybe changing machw.h

```
#ifdef M512
#define RAM_SIZE        (0x20000*1)
#else
#define RAM_SIZE        (0x20000*4)
#endif
```

or other options. Not everyone knows what value to insert. It can be, for example, 1 M

_The emulator takes up an awful lot of resources. An unnaturally large amount._  The processor even heats up. Other emulators don't have that.

**Comment by evansm7** [comment]
Try it and see, it’s part of the fun. :) 512 works, I haven’t tried higher (but interested in what you find out!). 

Can you describe what you mean about resources? Your comment lacks details that would help understand what’s going on. Memory measurement/process size?

The emulator itself is lightweight (intentionally, so it can run on an MCU with little memory or CPU power) so something else may be going on on your system. Linux? macOS? Something else? 

Message to anyone reading:  high-quality bug reports are important - I don’t have a lot of time to read this stuff so if you can’t debug something yourself at least give all possible info for others to debug for you. Thanks!

**Comment by evansm7** [comment]
Reopen if you have observations to share, thanks. Can’t recreate, so closing.
