### ISSUE TITLE
A Build Error

### ISSUE THREAD

**Issue by DanielTelles91** [evansm7/umac#7]
Hello.
I'm trying to build umac but there are some errors:

external/Musashi//m68kops.c:36456:10: error: ‘m68k_op_tst_16_aw’ undeclared here (not in a function); did you mean ‘m68k_op_tst_16_al’?

external/Musashi//m68kops.c:36496:10: error: ‘m68k_op_rts_32’ undeclared here (not in a function); did you mean ‘m68k_op_rtr_32’?

external/Musashi//m68kops.c:36503:10: error: ‘m68k_op_jsr_32_pcdi’ undeclared here (not in a function); did you mean ‘m68k_op_tst_32_pcdi’?

make: *** [Makefile:62: external/Musashi//m68kops.o] Erro 1

Could it be a dependency or gcc version problem?
Thank you

**Comment by evansm7** [comment]
Yo. It’s a Musashi file causing that, anything relevant in their upstream issues on GH?
Out of interest, what OS/compiler?

**Comment by DanielTelles91** [comment]
Thanks for the answer. 
Local files were corrupt. After performing a new git clone, the compilation was successful. 
Now Pico-Mac is running successfully :)
Thank you very much for your excellent work.

**Comment by DanielTelles91** [comment]
Thanks for the answer. 
Local files were corrupt. After performing a new git clone, the compilation was successful. 
Now Pico-Mac is running successfully :)
Thank you very much for your excellent work.
